<a href="https://colab.research.google.com/github/PETEROA/Predictive-Marketing/blob/main/Pred_Market.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as py
import pandas as pd
import seaborn as sns
import plotly.graph_objects as go

In [25]:
df = pd.read_csv("train.csv")

In [26]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [27]:
# The Stochastic Gradient Descent (SGD) Classifier
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


df_train = pd.read_csv("train.csv")


df_test = pd.read_csv("test.csv")

# Select features for prediction
selected_features = ['age', 'housing', 'default', 'poutcome', 'pdays', 'balance']

# Define features (X) and target variable (y) for training
X_train = df_train[selected_features]
y_train = df_train['y']  # 'y' is the target variable

# Define features (X) and target variable (y) for testing
X_test = df_test[selected_features]
y_test = df_test['y']

# Create a column "transformer" for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['age', 'pdays', 'balance']),  # Numerical features
        ('cat', OneHotEncoder(drop='first'), ['housing', 'default', 'poutcome'])  # Categorical features
    ])

# Create a pipeline with preprocessing and SGDClassifier
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', SGDClassifier(random_state=42))
])

# Train the classifier
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)


print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.89
Confusion Matrix:
[[3954   46]
 [ 438   83]]
Classification Report:
              precision    recall  f1-score   support

          no       0.90      0.99      0.94      4000
         yes       0.64      0.16      0.26       521

    accuracy                           0.89      4521
   macro avg       0.77      0.57      0.60      4521
weighted avg       0.87      0.89      0.86      4521



In [28]:
#K Nearest Neighbour
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


df_train = pd.read_csv("train.csv")


df_test = pd.read_csv("test.csv")

# Select features for prediction
selected_features = ['age', 'housing', 'default', 'poutcome', 'pdays', 'balance']

# Define features (X) and target variable (y) for training
X_train = df_train[selected_features]
y_train = df_train['y']  # 'y' is the target variable

# Define features (X) and target variable (y) for testing
X_test = df_test[selected_features]
y_test = df_test['y']

# Create a new column "transformer" for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first'), ['housing', 'default', 'poutcome'])
    ])

# Create a pipeline with preprocessing and KNeighborsClassifier
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', KNeighborsClassifier(n_neighbors=5))
])

# Train the classifier
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print results
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.83
Confusion Matrix:
[[3694  306]
 [ 485   36]]
Classification Report:
              precision    recall  f1-score   support

          no       0.88      0.92      0.90      4000
         yes       0.11      0.07      0.08       521

    accuracy                           0.83      4521
   macro avg       0.49      0.50      0.49      4521
weighted avg       0.79      0.83      0.81      4521



In [29]:
# Logistic Regression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


df_train = pd.read_csv("train.csv")


df_test = pd.read_csv("test.csv")


selected_features = ['age', 'housing', 'default', 'poutcome', 'pdays', 'balance']

# Define features (X) and target variable (y) for training
X_train = df_train[selected_features]
y_train = df_train['y']

# Define features (X) and target variable (y) for testing
X_test = df_test[selected_features]
y_test = df_test['y']

# Create a new column "transformer" for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['age', 'pdays', 'balance']),  # Numerical features
        ('cat', OneHotEncoder(drop='first'), ['housing', 'default', 'poutcome'])  # Categorical features
    ])

# Create a pipeline with preprocessing and Logistic Regression
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(random_state=42))
])

# Train the classifier
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)


print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.89
Confusion Matrix:
[[3955   45]
 [ 440   81]]
Classification Report:
              precision    recall  f1-score   support

          no       0.90      0.99      0.94      4000
         yes       0.64      0.16      0.25       521

    accuracy                           0.89      4521
   macro avg       0.77      0.57      0.60      4521
weighted avg       0.87      0.89      0.86      4521



In [30]:
#The Gaussian Naive Bayes (GNB) Classifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.pipeline import make_pipeline, FeatureUnion
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


df_train = pd.read_csv("train.csv")


df_test = pd.read_csv("test.csv")

# Selected features for prediction
selected_features = ['age', 'housing', 'default', 'poutcome', 'pdays', 'balance']

# Define features (X) and target variable (y) for training
X_train = df_train[selected_features]
y_train = df_train['y']

# Define features (X) and target variable (y) for testing
X_test = df_test[selected_features]
y_test = df_test['y']


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), make_column_selector(dtype_include='number')),
        ('cat', OneHotEncoder(drop='first'), make_column_selector(dtype_include='object'))
    ])

# Create a pipeline with preprocessing and Gaussian Naive Bayes
pipeline = make_pipeline(preprocessor, GaussianNB())

# Train the classifier
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)


print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.85
Confusion Matrix:
[[3699  301]
 [ 377  144]]
Classification Report:
              precision    recall  f1-score   support

          no       0.91      0.92      0.92      4000
         yes       0.32      0.28      0.30       521

    accuracy                           0.85      4521
   macro avg       0.62      0.60      0.61      4521
weighted avg       0.84      0.85      0.84      4521



In [31]:
# The Decision Tree Classifier,
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder


df_train = pd.read_csv("train.csv")


df_test = pd.read_csv("test.csv")

# Selected features for prediction
selected_features = ['age', 'housing', 'default', 'poutcome', 'pdays', 'balance']

# Define features (X) and target variable (y) for training
X_train = df_train[selected_features]
y_train = df_train['y']

# Define features (X) and target variable (y) for testing
X_test = df_test[selected_features]
y_test = df_test['y']

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first'), ['housing', 'default', 'poutcome'])
    ],
    remainder='passthrough'  # Pass through the other features as-is
)

# Create a pipeline with preprocessing and DecisionTreeClassifier
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

# Train the classifier
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)


print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.99
Confusion Matrix:
[[3998    2]
 [  55  466]]
Classification Report:
              precision    recall  f1-score   support

          no       0.99      1.00      0.99      4000
         yes       1.00      0.89      0.94       521

    accuracy                           0.99      4521
   macro avg       0.99      0.95      0.97      4521
weighted avg       0.99      0.99      0.99      4521



In [32]:
#The Random Forest Classifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder


df_train = pd.read_csv("train.csv")

df_test = pd.read_csv("test.csv")

# Select features for prediction
selected_features = ['age', 'housing', 'default', 'poutcome', 'pdays', 'balance']

# Define features (X) and target variable (y) for training
X_train = df_train[selected_features]
y_train = df_train['y']

# Define features (X) and target variable (y) for testing
X_test = df_test[selected_features]
y_test = df_test['y']

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first'), ['housing', 'default', 'poutcome'])
    ],
    remainder='passthrough'  # Pass through the other features as-is
)

# Create a pipeline with preprocessing and RandomForestClassifier
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

# Train the classifier
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the classifier
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)


print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.99
Confusion Matrix:
[[3993    7]
 [  50  471]]
Classification Report:
              precision    recall  f1-score   support

          no       0.99      1.00      0.99      4000
         yes       0.99      0.90      0.94       521

    accuracy                           0.99      4521
   macro avg       0.99      0.95      0.97      4521
weighted avg       0.99      0.99      0.99      4521

